### ISSUE TITLE
지뢰지도 생성 알고리즘 만들기

### ISSUE THREAD

**Issue by ysp-laonpeople** [KHD-laonpeople/MineSweeper#3]
## 지뢰지도 생성 알고리즘
- 보드의 가로,세로 그리고 지뢰수량을 입력받아 지뢰지도를 생성합니다.

### 지뢰 생성 함수
- 가로,세로,지뢰수를 입력받아 지뢰위치를 리턴합니다.
``` c#
bool[,] CreateMineLocations(int width, int height, int mineCount)
{
    //지뢰는 랜덤하게 생성됩니다.
    //지뢰는 중복되지 않습니다.
    return null;
}
```
  
### 지뢰지도 생성 함수
``` c#
int[,] CreateMineMap(bool[,] mineLocations)
{
    //주변8칸의 지뢰수를 반환합니다.
    //주변에 지뢰가 없거나, 해당위치가 지뢰인 경우에는 0을 반환합니다.
    return null;
}
```
  
- 위 함수를 구현해주세요.
@KHD-laonpeople

**Comment by ghost** [comment]
지뢰 생성 함수, 지뢰지도 생성 함수 완료했습니다.

**Comment by ysp-laonpeople** [comment]
구현함수 부분을 찾을수가 없습니다.
코멘트로 코드를 추가하시거나. 함수 코드를 링크해주세요
> 예시
https://github.com/KHD-laonpeople/MineSweeper/blob/938c79bcf27dae3eb653696e28b234b492cb45b9/MINESWEEPER/MINESWEEPER/BoardData.cs#L18-L28
@KHD-laonpeople

**Comment by ysp-laonpeople** [comment]
* 코드 링크 거는 방법
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

**Comment by KHD-laonpeople** [comment]
public bool[,] CreateMineLocations(int x, int y, int mine)
        {
            bool[,] mineLocation = new bool[y, x];
            for(int i = 0; i < y; i++)
            {
                for(int j = 0; j < x; j++)
                {
                    mineLocation[i, j] = buttonDatas[i][j].GetMine();
                }
            }
            return mineLocation;
        }


        public int[,] CreateMineMap(bool[,] mineLocations)
        {
            int[,] mineMap = new int[mineLocations.GetLength(0), mineLocations.Length / mineLocations.GetLength(0)];
            for(int i = 0; i < y; i++)
            {
                for(int j = 0; j < x; j++)
                {
                    mineMap[i, j] = mineLocations[i,j] ? 0 : CheckRound_MineCount(i, j);
                }
            }
            return mineMap;
        }
    }

**Comment by KHD-laonpeople** [comment]
https://github.com/KHD-laonpeople/MineSweeper/blob/569d622adabdb95799e73e01fd610d1656e35bd1/MINESWEEPER/MINESWEEPER/BoardData.cs#L138-L163

**Comment by ghost** [comment]
지뢰 위치 정보 출력
https://github.com/KHD-laonpeople/MineSweeper/blob/569d622adabdb95799e73e01fd610d1656e35bd1/MINESWEEPER/MINESWEEPER/BoardData.cs#L138-L149

주변 지뢰 개수 정보 출력
https://github.com/KHD-laonpeople/MineSweeper/blob/569d622adabdb95799e73e01fd610d1656e35bd1/MINESWEEPER/MINESWEEPER/BoardData.cs#L151-L162

**Comment by ysp-laonpeople** [comment]
- 전역변수접근없이 순수기능구현코드 업로드 부탁드립니다.
- 코드확인후 제가 close 하겠습니다.
@KHD-laonpeople

**Comment by ghost** [comment]
지뢰 생셩 함수는 주신 예시보다 좋은 방법이 생각나지 않아 그대로입니다.
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/BoardData.cs#L99-L120

주변 지뢰 개수 배열입니다.
시간이 되면 말씀해주신 함수안에 Action을 통해 다른 동작을 하도록 구현해보겠습니다.
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/BoardData.cs#L122-L153

**Comment by ysp-laonpeople** [comment]
- 앞으로 프로젝트를 관리하게되면 이슈관리가 가장중요합니다. ^^
- 이슈라고해서 문제라고 생각하지말고 용어차이입니다.
- 어디는 Task 어디는 Issue 등등 작은 작업단위라고 생각하시면 됩니다.
- 항상 열려있는 이슈는 머가있고 추적중인지? 종료되었으면 반드시 종료 관리를 해주셔야합니다.
- 나중에 tag관련해서도 공유드리겠습니다.
@KHD-laonpeople 

해당건도 완료되었으니 종료처리부탁드려용
