### ISSUE TITLE
과제 2. 추가 요구사항 반영 요청

### ISSUE THREAD

**Issue by ysp-laonpeople** [KHD-laonpeople/MineSweeper#4]
## 추가 요구사항 반영 요청
- 개발 완료된 지뢰찾기에 추가 요구사항을 반영합니다.
- 요구사항 반영에 필요한 추가 리소스와 일정이 필요합니다.

## 요구사항
- [x] 지뢰 생성 기능의 lib 제공
  - [x] 지뢰 지도 생성 기능 : 위치,지뢰여부,인접지뢰수 가 포함된 정보
  - [x] 기능이 명세되어있는 문서 : class, function별 기능 및 in/out 정보 기술
- [x] 기록 측정 기능 추가
  - [x] 성공 시간 측정 가능
  - [x] top 5 기록 저장,갱신 기능
  
### 개발요청사항 (필수아님)
- [ ] xaml과 cs 분리 요청
  - MVVM 패턴으로 분리 요청
- [ ] 지뢰 지도 데이타 모델 생성
  - [ ] json으로 지뢰지도 저장,불러오기 구현
  
## 제약조건
- 

## 기한
- 개발계획서, 설계문서 제출: 2022.02.15
- 진행사항 리뷰 : 2022.02.18
- 진행사항 공유 : 상시

@KHD-laonpeople

**Comment by ghost** [comment]
1-1 지뢰 지도 생성 기능 : 위치,지뢰여부,인접지뢰수 가 포함된 정보
지뢰 위치, 지뢰 여부 정보 반환
https://github.com/KHD-laonpeople/MineSweeper/blob/7eef26b7bccfe099a0ea3e6a64398458caa5993e/MINESWEEPER/MINESWEEPER/BoardData.cs#L146-L157
인접 지뢰수 반환
https://github.com/KHD-laonpeople/MineSweeper/blob/7eef26b7bccfe099a0ea3e6a64398458caa5993e/MINESWEEPER/MINESWEEPER/BoardData.cs#L159-L172

1-2 기능이 명세되어있는 문서 : class, function별 기능 및 in/out 정보 기술
https://github.com/KHD-laonpeople/MineSweeper/blob/7eef26b7bccfe099a0ea3e6a64398458caa5993e/MINESWEEPER/MINESWEEPER%20Class_Funcions.xlsx

**Comment by ghost** [comment]
타이머를 통해 점수 기능까지 추가하고 MVVM 패턴으로 분리 진행하겠습니다.
MVVM 패턴 분리 진행하며 기존의 이미지도 MahApp icon으로 변경하도록 하겠습니다.

**Comment by ysp-laonpeople** [comment]
- 첫번째 함수의경우 외부 변수가 내부 기능구현에 영향을 주는 경우라 적합하지 않습니다.
- buttonDatas변수를 외부에서 변경시 동일한 입력임에도 불구하도 다른 출력을 가져가게됩니다.

``` csharp
var board = new BardData(5,5,5);
var mines = board.CreateMineLocations(5,5,5);
//mine이 없는 배열이 리턴되지 않을까요? board.GameBoardCreate()가 필수조건이 되는 상황이네요
var mines = board.CreateMineLocations(10,10,10);
//오류 발생하지 않을까요??
```

- 두번째 함수의 경우에도 외부 변수가 내부기능에 영향을 주는경우라 적합하지 않습니다.
- x,y가 10,10 인 경우 mineLocations길이가 5x5라면 index 접근 오류가 발생합니다.
- CheckRound_MineCount함수의 경우에도 전역변수인 buttonDatas를 사용하므로 잠재오류를 가지고있습니다.

- 단일함수는 순수하게 입출력에만 종속적으로 기능을 구현할 수 있도록 연습해봅시다.

**Comment by ysp-laonpeople** [comment]
- 첫번째 함수 구현예제 공유합니다.
- 주어진 지뢰수만큼만만 순환하도록 구현할 것 같습니다.
- 중복될 경우를 가정하여 while문으로 적용하였습니다.
- 연산하기 쉽도록 1차배열로 계산 후 2차배열로 반환하였습니다. (필요시 converter로 별도 구현해도 좋음)
- 입력값은 모두 0보다 커야하고 x,y 정상입력시 크기는 정상 크기로 반환하였습니다.
```csharp
        public bool[,] CreateMineLocations(int x, int y, int mine)
        {
            bool[,] mines = new bool[y, x];
            if (x > 0 && y > 0 && mine > 0)
            {
                bool[] tmp = new bool[mines.Length];
                Random rnd = new Random();
                do
                {
                    tmp[rnd.Next(0, tmp.Length)] = true;
                } while (tmp.Count(g => g) < mine);
                Buffer.BlockCopy(tmp, 0, mines, 0, tmp.Length);
            }
            return mines;
        }
```
@KHD-laonpeople

**Comment by ghost** [comment]
확인했습니다.
독립적으로 작동하는 방식으로 다시 진행해보겠습니다.

**Comment by ghost** [comment]
Buffer 기능은 처음 알았습니다. 엄청 편리하네요 ㅎㅎ.
람다식은 몇 번 봤었는데 아직 익숙하지 않아 잘 생각나지 않는 것 같습니다.
좀 더 숙달 작업이 필요할 것 같네요.

**Comment by ysp-laonpeople** [comment]
- 람다식은 익숙해져야 c#이 편리해질거에요.
- 코드도 간편해지구요.
- 의존성 없는 함수를 구현해야 아래같이 테스트가 가능합니다.(지금은 전부 통과되진 않겠죠?)
``` csharp
  - CreateMineLocations(0,0,0)
  - CreateMineLocations(-1,0,0)
  - CreateMineLocations(0,-1,0)
  - CreateMineLocations(0,0,-1)
  - CreateMineLocations(1000000000000,10000000000000,0)
```
@KHD-laonpeople

**Comment by ghost** [comment]
02.17 ~ 02.18 NEPES 관련 출장으로 인해 리뷰 02.18이 아닌 02.21로 변경 요청드립니다.
필수가 아니라고하신 MVVM 분리, json 파일 저장 및 불러오기 기능은 25일까지 진행하도록 하겠습니다.

**Comment by ghost** [comment]
2-1. 타이머 측정을 위한 함수입니다.
https://github.com/KHD-laonpeople/MineSweeper/blob/3ed803612de83187188351e98bc80c573496d7b9/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L124-L126
https://github.com/KHD-laonpeople/MineSweeper/blob/3ed803612de83187188351e98bc80c573496d7b9/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L130-L138

2-2. csv 파일 읽기, 쓰기를 통한 랭킹 관련 함수입니다.
json 형식, sort 형식으로 변환해보겠습니다.
https://github.com/KHD-laonpeople/MineSweeper/blob/3ed803612de83187188351e98bc80c573496d7b9/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L231-L265

**Comment by ghost** [comment]
랭킹 시스템 JSON을 사용하도록 변경했습니다.
json 파일 불러오기(파일이 없을 시 생성하도록 구성)
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L242-L260

JSON파일 저장 및 정렬, 값 반환
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L266-L293

JSON 데이터 Score값을 통해 정렬
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L261-L265

랭킹 5등까지만 출력하도록 출력 코드 구성
https://github.com/KHD-laonpeople/MineSweeper/blob/4e9b95fa2d7c714e55444896da6c06f7cab1ee44/MINESWEEPER/MINESWEEPER/MainWindow.xaml.cs#L229-L237

**Comment by ghost** [comment]
적다보니 데이터 저장 자체를 5등까지만 저장해야 데이터 관리에 효율적일 것 같아서 
5등까지만 저장하도록 변경하겠습니다.

**Comment by ysp-laonpeople** [comment]
- 기간 만료되어 해당 이슈는 close 처리부탁드립니다.
- 개발 잔여항목으로 신규 이슈 추가 부탁드립니다.
  - 개발 완료 계획일자 명시 필수
@KHD-laonpeople
