### ISSUE TITLE
핵심 키워드 조사 및 정리

### ISSUE THREAD

**Issue by ysp-laonpeople** [KHD-laonpeople/MineSweeper#5]
### 핵심 키워드 조사 및 정리
- 업무 중 또는 코드리뷰 중 확인된 핵심 키워드를 조사하여 정리합니다.
- 업무 중 또는 코드리뷰 중 모르는 키워드에 대해 조사하여 정리합니다.

### 작업 방법
- 용어 사전 집을 wiki에 문서로 생성하시거나 wiki 메인 페이지에 링크를 추가합니다.
- 용어별로 조사한 내용과 이해한 내용을 wiki 문서로 추가합니다.
  - 개일 블로그나 페이지가 있는경우 링크로 참조해도 무관합니다.
- 하루하루 확인 된 키워드는 문서로 먼저 등록합니다.
  - 상세 내용을 추후에 채우더라도 누락되지 않도록 등록합니다.
- 비지니스영역과 분리합니다.
  - 예를들어 MVVM(무관), NEPES(연관), MarkDown(무관) 등

@KHD-laonpeople

**Comment by ghost** [comment]
현재 Notion을 사용하여 정리중입니다.
링크를 첨부하려고 확인해보니 개인만 접근가능하고 멤버 추가는 유료 서비스라서 이미지 첨부로 대체합니다.
![image](https://user-images.githubusercontent.com/87353500/155436225-0ecc17b9-8ee8-494c-ab14-987bbdc8cc8a.png)
02.23 진행한 LightController 및 이전에 주신 KeyWord들도 적어두고 내용 추가하는식으로 진행하고 있습니다.

**Comment by ysp-laonpeople** [comment]
### 공유됩니다.
- 그럴리가없는데 ??? 역시 공유가능하네요 ㅋㅋ
#### 샘플페이지
- https://www.notion.so/50523238ff4844c6b8a3b86d59e93af0
#### 공유 방법
* ![image](https://user-images.githubusercontent.com/84366784/155474304-7c4e3676-fc86-4e32-a20b-73f2c0d8eaa4.png)
* 우상단 공유로 공유가능하고 초대하면 협업도되네요
#### 라이센스
- 무료는 5명까지 협업가능. 그 이상이면 유료필요
- https://www.notion.so/pricing
- 클라우드 사용하면 용량제한 상관없고 5명이내 협업이면 무료 충분합니다.
@KHD-laonpeople

**Comment by KHD-laonpeople** [comment]
노션 주소입니다.
https://northern-theater-d0a.notion.site/C-55efce9933b240da8d49ab523dbf880c

접근 아이디 주시면 초대 방식으로 변경하겠습니다.

**Comment by ghost** [comment]
노션 접속 링크입니다.
https://northern-theater-d0a.notion.site/6a9c0377bd4e4871bc5764df2cf6102f

**Comment by ysp-laonpeople** [comment]
* 별도 보고과정은 필요없습니다.
* 추후 신규입사자나 팀원간 공유를 위해 사용하면 좋을것 같네요
